### ISSUE TITLE
Harvest Settings doesn't work

### ISSUE THREAD

**Issue by BrunoPourtierAtOyez** [singlemind/redmine_harvest_smc#1]
Hi, 
I have just installed this Redmine plugins and I've been able to configure the plugin, an admin user, but I can't access to Harvest Settings page.
I always got :

> Internal error
> An error occurred on the page you were trying to access.
> If you continue to experience problems please contact your Redmine administrator for assistance.
> If you are the Redmine administrator, check your log files for details about the error.
> Back

**Comment by BrunoPourtierAtOyez** [comment]
Here a more explicit error from the redmine production.log file:

``` ruby
Started GET "/harvest_settings" for xxx.xxx.xxx.xxx at Fri Sep 20 09:59:10 +0200 2013
Processing by HarvestEntryController#harvest_settings as HTML
Current user: admin (id=1)
Completed 500 Internal Server Error in 24ms
SyntaxError (/redmine/plugins/redmine_harvest_smc/app/models/harvest_project.rb:6: syntax error, unexpected ':', expecting kEND
scope :active_only, where: project_active=>true
^):
```

**Comment by mikeyhill** [comment]
Same here.  I've updated the user/plugin settings with my harvest info, but settings doesn't work at all.  I get the exact same error as above (syntax).  Can plugin creator give us an idea what causes this so that I can fix?

**Comment by edwardsharp** [comment]
Drat, thanks for the report. I think this will be an easy fix, should be able to get an update in the next couple of days...

**Comment by mikeyhill** [comment]
Np, let me know if you need more info from me - thanks :)

**Comment by BrunoPourtierAtOyez** [comment]
Thank you, it would be great to have a fix to this issue. Let me know also if you need more informations.

**Comment by edwardsharp** [comment]
Hi, yes, please do report the version of Redmine, Rails, and Ruby that you're using that is causing this problem.

**Comment by BrunoPourtierAtOyez** [comment]
Here the Redmine configuration

> Environment:
> 
> > Redmine version                          2.2.4.stable.11838
> > Ruby version                             1.8.7 (x86_64-linux)
> > Rails version                            3.2.13
> > Environment                              production
> > Database adapter                         MySQL
> 
> Redmine plugins:
> 
> > redmine_bitbucket                        0.2.0
> > redmine_harvest_smc                      0.0.1

**Comment by edwardsharp** [comment]
Ah yes, it's likely to do with using ruby 1.8.7 and how it handles block scope; which changed in the 1.9.x versions of ruby. I'd suggest moving to 1.9.3 as 1.8.7 has reached it's end of life: https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/

**Comment by mikeyhill** [comment]
Same here:

Environment:
  Redmine version                          2.3.1.stable
  Ruby version                             1.8.7 (x86_64-linux)
  Rails version                            3.2.13
  Environment                              production
  Database adapter                         MySQL
Redmine plugins:
  redmine_charts2                          0.2.1
  redmine_hipchat                          2.0.0
  redmine_inline_note_images_plugin        0.0.1
  redmine_lightbox                         0.0.1
  redmine_milestones                       1.0.0-pro-alpha1

(smc plugin removed temporarily).  I'll check into moving up to 1.9.3 - thanks for the advice.

**Comment by BrunoPourtierAtOyez** [comment]
I have updated RUBY on 1.9.3, but I still have an error message

``` ruby
Started GET "/harvest_settings" for xxx.xxx.xxx.xxx at 2013-11-08 14:42:54 +0100
Processing by HarvestEntryController#harvest_settings as HTML
  Current user: admin (id=1)
Completed 500 Internal Server Error in 67ms

SyntaxError (/xxx/redmine/plugins/redmine_harvest_smc/app/models/harvest_project.rb:6: syntax error, unexpected tASSOC, expecting keyword_end
    scope :active_only, where: project_active=>true
                                               ^):
  activesupport (3.2.13) lib/active_support/dependencies.rb:251:in `require'
  activesupport (3.2.13) lib/active_support/dependencies.rb:251:in `block in require'
  activesupport (3.2.13) lib/active_support/dependencies.rb:236:in `load_dependency'
  activesupport (3.2.13) lib/active_support/dependencies.rb:251:in `require'
  activesupport (3.2.13) lib/active_support/dependencies.rb:359:in `require_or_load'
  activesupport (3.2.13) lib/active_support/dependencies.rb:502:in `load_missing_constant'
  activesupport (3.2.13) lib/active_support/dependencies.rb:192:in `block in const_missing'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in `each'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in `const_missing'
  activesupport (3.2.13) lib/active_support/dependencies.rb:514:in `load_missing_constant'
  activesupport (3.2.13) lib/active_support/dependencies.rb:192:in `block in const_missing'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in `each'
  activesupport (3.2.13) lib/active_support/dependencies.rb:190:in `const_missing'
  plugins/redmine_harvest_smc/app/controllers/harvest_entry_controller.rb:59:in `harvest_settings'
  actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.13) lib/active_support/callbacks.rb:469:in `_run__4264928804368250863__process_action__3916557240657050477__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.13) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in `call'
  rack-openid (1.3.1) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.13) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `_run__2073286198909737364__call__2051879570739733644__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in `call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  passenger (4.0.23) lib/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
  passenger (4.0.23) lib/phusion_passenger/request_handler/thread_handler.rb:140:in `accept_and_process_next_request'
  passenger (4.0.23) lib/phusion_passenger/request_handler/thread_handler.rb:108:in `main_loop'
  passenger (4.0.23) lib/phusion_passenger/request_handler.rb:441:in `block (3 levels) in start_threads'
```

Any idea?

**Comment by edwardsharp** [comment]
Would you please paste line 6 of /xxx/redmine/plugins/redmine_harvest_smc/app/models/harvest_project.rb

**Comment by BrunoPourtierAtOyez** [comment]
``` ruby
class HarvestProject < ActiveRecord::Base
  unloadable
  validates_presence_of :project_name, :on => :create, :message => "can't be blank"

    scope :uniq_project, select("DISTINCT project_name")
    scope :active_only, where: project_active=>true

end
```

**Comment by edwardsharp** [comment]
Hmm, please make sure you've got the most up-to-date version of the plugin
from github-- as that line is very much out of date. It should read like
this:
https://github.com/singlemind/redmine_harvest_smc/blob/master/app/models/harvest_project.rb#L6

**Comment by funzie19** [comment]
I have the same problem as described above. And I have the most updated branch version. Give me a few minutes and I will post the error message.

**Comment by funzie19** [comment]
Even with an user set I get the error.

Started GET "/harvest_settings" for 10.0.21.186 at 2013-11-07 06:58:46 -0500
Processing by HarvestEntryController#harvest_settings as HTML
  Current user: xxx (id=28)
NO USER SET
NO USER SET
Completed 500 Internal Server Error in 11ms

ActiveRecord::StatementInvalid (PG::UndefinedColumn: ERROR:  column "destroyed" does not exist
LINE 1: ...ings".\* FROM "harvest_settings"  WHERE (status != "destroyed...
                                                             ^
: SELECT "harvest_settings".\* FROM "harvest_settings"  WHERE (status != "destroyed")):
  activerecord (3.2.13) lib/active_record/connection_adapters/postgresql_adapter.rb:1161:in `exec'
  activerecord (3.2.13) lib/active_record/connection_adapters/postgresql_adapter.rb:1161:in`exec_no_cache'
  activerecord (3.2.13) lib/active_record/connection_adapters/postgresql_adapter.rb:660:in `block in exec_query'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract_adapter.rb:280:in`block in log'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract_adapter.rb:275:in`log'
  activerecord (3.2.13) lib/active_record/connection_adapters/postgresql_adapter.rb:659:in `exec_query'
  activerecord (3.2.13) lib/active_record/connection_adapters/postgresql_adapter.rb:1256:in`select'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in`block in select_all'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/query_cache.rb:75:in `cache_sql'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/query_cache.rb:61:in`select_all'
  activerecord (3.2.13) lib/active_record/querying.rb:38:in `block in find_by_sql'
  activerecord (3.2.13) lib/active_record/explain.rb:41:in`logging_query_plan'
  activerecord (3.2.13) lib/active_record/querying.rb:37:in `find_by_sql'
  activerecord (3.2.13) lib/active_record/relation.rb:171:in`exec_queries'
  activerecord (3.2.13) lib/active_record/relation.rb:160:in `block in to_a'
  activerecord (3.2.13) lib/active_record/explain.rb:41:in`logging_query_plan'
  activerecord (3.2.13) lib/active_record/relation.rb:159:in `to_a'
  activerecord (3.2.13) lib/active_record/relation.rb:189:in`exec_queries'
  activerecord (3.2.13) lib/active_record/relation.rb:160:in `block in to_a'
  activerecord (3.2.13) lib/active_record/explain.rb:41:in`logging_query_plan'
  activerecord (3.2.13) lib/active_record/relation.rb:159:in `to_a'
  activerecord (3.2.13) lib/active_record/relation/finder_methods.rb:159:in`all'
  activerecord (3.2.13) lib/active_record/querying.rb:5:in `all'
  plugins/redmine_harvest_smc/app/controllers/harvest_entry_controller.rb:57:in`harvest_settings'
  actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:167:in`process_action'
  actionpack (3.2.13) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
  activesupport (3.2.13) lib/active_support/callbacks.rb:469:in `_run__1784415845380973953__process_action__3250354282757165253__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in`__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in`run_callbacks'
  actionpack (3.2.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.13) lib/action_controller/metal/rescue.rb:29:in`process_action'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:30:in`block in process_action'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.13) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
  activesupport (3.2.13) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:29:in`process_action'
  actionpack (3.2.13) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.13) lib/active_record/railties/controller_runtime.rb:18:in`process_action'
  actionpack (3.2.13) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:45:in`process'
  actionpack (3.2.13) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.13) lib/action_controller/metal/rack_delegation.rb:14:in`dispatch'
  actionpack (3.2.13) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in`call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:36:in`call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in`each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.13) lib/action_dispatch/routing/route_set.rb:612:in`call'
  rack-openid (1.4.0) lib/rack/openid.rb:98:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/best_standards_support.rb:17:in`call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/params_parser.rb:21:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in`context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/cookies.rb:341:in`call'
  activerecord (3.2.13) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.13) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in`_run__956971053897661467__call__3276997873868324539__callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.13) lib/active_support/callbacks.rb:385:in`_run_call_callbacks'
  activesupport (3.2.13) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.13) lib/action_dispatch/middleware/callbacks.rb:27:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/debug_exceptions.rb:16:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.13) lib/rails/rack/logger.rb:32:in`call_app'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.13) lib/active_support/tagged_logging.rb:22:in`tagged'
  railties (3.2.13) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.13) lib/action_dispatch/middleware/request_id.rb:22:in`call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in`call'
  activesupport (3.2.13) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in`call'
  actionpack (3.2.13) lib/action_dispatch/middleware/static.rb:63:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in`forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in`lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in`call'
  railties (3.2.13) lib/rails/engine.rb:479:in `call'
  railties (3.2.13) lib/rails/application.rb:223:in`call'
  railties (3.2.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
  thin (1.6.1) lib/thin/connection.rb:82:in`block in pre_process'
  thin (1.6.1) lib/thin/connection.rb:80:in `catch'
  thin (1.6.1) lib/thin/connection.rb:80:in`pre_process'
  thin (1.6.1) lib/thin/connection.rb:55:in `process'
  thin (1.6.1) lib/thin/connection.rb:41:in`receive_data'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in `run_machine'
  eventmachine (1.0.3) lib/eventmachine.rb:187:in`run'
  thin (1.6.1) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.1) lib/thin/server.rb:162:in`start'
  thin (1.6.1) lib/thin/controllers/controller.rb:87:in `start'
  thin (1.6.1) lib/thin/runner.rb:200:in`run_command'
  thin (1.6.1) lib/thin/runner.rb:156:in `run!'
  thin (1.6.1) bin/thin:6:in`<top (required)>'
  /usr/local/bin/thin:23:in `load'
  /usr/local/bin/thin:23:in`<main>'

**Comment by BrunoPourtierAtOyez** [comment]
For me it worked. My folder was already up-to-date but I fetch and reset the connection.
Now it worked.

Thank you for your help.

**Comment by edwardsharp** [comment]
@BrunoPourtierAtOyez good to hear! 

@funzie19 please don't hijack the thread, you seem to be having separate issues. Did you run the plugin db migrations?  If not please open an issue and paste your version of Ruby, Rails, & Redmine...
